version: '3'

services:
  ae4878_assignments:
    build:
      context: .
      dockerfile: .Dockerfile
      args:
        NB_UID: ${UID}
        NB_GID: ${GID}
    ports:
      - 8888:8888
    environment:
      - GRANT_SUDO=1
      - JUPYTER_ENABLE_LAB=1
      - RESTARTABLE=1
    volumes:
      - ./:/home/jovyan/ae4878_assignments
